# See src/contribs/docker/README.md for instructions

services:
    davmail:
        container_name: davmail
        hostname: davmail
        image: ghcr.io/mguessan/davmail:stable
        restart: unless-stopped
        ports:
            - 127.0.0.1:1025:1025 # SMTP
            - 127.0.0.1:1143:1143 # IMAP
        volumes:
            - ./config:/config
